{"errorMessage": "An error occurred (AccessDenied) when calling the AssumeRole operation: User: arn:aws:sts::548054344313:assumed-role/mt-2025/mt-relogin-vm-lambda is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::548054344313:role/mt-restart-vm-role-owjfzrs8", "errorType": "ClientError", "requestId": "bad0acb2-5bc0-45dc-a504-ad53237033cf", "stackTrace": ["  File \"/var/task/lambda.py\", line 23, in lambda_handler\n    ssm_client = assume_role(role_arn)\n", "  File \"/var/task/lambda.py\", line 7, in assume_role\n    assumed_role = sts_client.assume_role(\n", "  File \"/var/runtime/botocore/client.py\", line 569, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n", "  File \"/var/runtime/botocore/client.py\", line 1023, in _make_api_call\n    raise error_class(parsed_response, operation_name)\n"]}